var itemLabelsShouldBe = function ( _filter ) {
  var args = Array.prototype.slice.call( arguments ).splice( 1 );

  _filter.list.$list.children().should.have.a.lengthOf( args.length );
  args.forEach( function ( _value, _i ) {
    _filter.list.$list.find( ":nth-child(" + ( _i + 1 ) + ")" ).text().should.equal( _value );
  } );
};

describe( "standard tests", function () {

  it( "the plugin should have rendered", function () {
    var $section = $( "section.test" );
    $section.find( "[data-sc-filtered-list]" ).length.should.be.greaterThan( 0 );
    $section.find( ".sc-filtered-list-container" ).length.should.be.greaterThan( 0 );
    $section.find( ".sc-filtered-list-header" ).length.should.be.greaterThan( 0 );
    $section.find( ".sc-filtered-list-input" ).length.should.be.greaterThan( 0 );
  } );

  it( "each filter should have `data` that contains the instantiated `FilteredList` object", function () {

    $( "[data-sc-filtered-list]" ).each( function ( _i, _el ) {
      $( _el ).data( "scfilteredlist" ).should.be.FilteredList;
    } );

  } );

  it( "each filter should be wrapped in a span generated by the lib", function () {
    $( "[data-sc-filtered-list]" ).each( function ( _i, _el ) {
      var $el = $( _el );
      /span/i.test( $el.parent()[ 0 ].tagName ).should.be.true;
      $el.parent().is( ".sc-filtered-list" ).should.be.true;
    } );
  } );

  it( "each filter should have the right width", function ( _done ) {

    this.slow( 5000 );

    var q = async.queue( function ( _filter, _callback ) {
      var filter = _filter;

      filter.list.open();

      setTimeout( function () {
        var widthIsRight = Math.abs( filter.list.$el.outerWidth() - filter.__config.defaults.width ) < 3;
        widthIsRight.should.be.true;
        filter.list.close();

        setTimeout( function () {
          _callback();
        }, 100 );

      }, 100 );

    }, 3 );

    q.drain = function () {
      _done();
    }

    $( "[data-sc-filtered-list]" ).each( function ( _i, _el ) {
      q.push( $( _el ).data( "scfilteredlist" ) );
    } );

  } );

} );